Bowling submit
fronts1231/ruby-practices pull request #8
Opened 2021-01-14 09:09 UTC by fronts1231

実行コードとテストコードを提出します。ご確認お願いいたします。

2021-01-19 02:39 UTC, u1tnk requested changes

2021-01-19 02:39 UTC, u1tnk commented on 04.bowling/bowling.rb
> +def bowling1(shots)
メソッド名は何をするものなのかをちゃんと分かるように付けましょう。
bowlingは良いとして1〜3は何をやっているか分からないのでNGです。

2021-01-19 02:39 UTC, u1tnk commented on 04.bowling/bowling.rb
> +    number = i * 2
ちょっと分かりづらいコードになってますね。
この課題としては大丈夫なレベルなのでOOP版のプラクティスでは改善するように気をつけてください 💪

2021-01-19 08:00 UTC, fronts1231 commented on 04.bowling/bowling.rb
> +def bowling1(shots)
ご指摘ありがとうございます。何をするものかわかるよう、動詞をつけたメソッド名に修正しました。

2021-01-19 08:03 UTC, fronts1231 commented on 04.bowling/bowling.rb
> +    number = i * 2
こちらもコメントありがとうございます。より複雑なロジックが必要になった際にも何をやっているのか読み手がわかるよう、他の方の提出物も拝見し勉強しておきます。

2021-01-20 01:40 UTC, u1tnk commented on 04.bowling/bowling.rb
> +  p point
メソッドが calculate_scoreになっているので、メソッドで返ってきたポイントを出力した方が良いですね。
こういうイメージです。
`p bowling(ARGV[0])`

メソッドの名前以外の事はしないようにしましょう。

2021-01-20 02:00 UTC, fronts1231 commented on 04.bowling/bowling.rb
> +  p point
ありがとうございます。
calculate_scoreでは出力までカバーせずpointを返すところまでに留め（47行目）、50行目で結果出力、という形に変更しました。この理解で間違いないでしょうか？

2021-01-22 11:41 UTC, merged